### ISSUE TITLE
[BUG] auto_assign.yml 추가 및 삭제

### ISSUE THREAD

**Issue by KimDaeSeong8721** [DeveloperAcademy-POSTECH/toGather#110]
# 🐞 버그 설명
| 문제 발생 일시 |  발생 위치  | 발생 조건 |
| --- | --- | --- | 
|  |  |  | 

## 증상 

 리뷰어 자동 생성하기 위해서 auto_assign.yml 파일 new-dev에 추가했는데 compare & Pull Request  to main이 계속 뜸.
 그래서 다시 삭제했는데 pr하라는 메시지 계속 뜸. 죄송함다..

**Comment by yudonlee** [comment]
auto_assign을 main branch에 추가하면 되지 않을까요?
