### ISSUE TITLE
[FEAT] Saving Struct 데이터 구조 변경

### ISSUE THREAD

**Issue by limhyoseok** [DeveloperAcademy-POSTECH/toGather#29]
## 💡 Issue

progressCircle 및 날짜 계산 로직을 구현하는 과정에서 데이터 구조 변경의 필요성을 느낌

|기존|변경|
|-|-|
|<img width="358" alt="image" src="https://user-images.githubusercontent.com/59302419/173234694-994d3b09-18a3-453c-99b1-ecd87a9dc282.png">|<img width="354" alt="image" src="https://user-images.githubusercontent.com/59302419/173234700-74f20e68-f5cc-46cb-a9b1-dfa8472bc369.png">|

- weekInfo 추가 : 주차별 ThisWeek 저장정보를 담을 변수가 필요하다. 
- totalWeeks -> goalWeeks 변경 : 저축 실패할 경우 weeks 늘어나기 때문에 처음 목표한 goalWeeks를 저장할 변수가 필요. 늘어난 weeks는 weekInfo로 계산 가능
- progressPercent 제거 : weekInfo로 부터 매번 계산해야하기 때문에 불필요

## 📝  todo
- [x] 변경사항에 맞게 코드 리팩토링

**Comment by KimDaeSeong8721** [comment]
오 너무 좋습니다. goalWeeks가 더 쉽게 이해가 되네요.
그리고 더미데이터 saveList부분처럼 Saving마다 ThisWeek 배열 받는 변수 좋습니다!!

**Comment by limhyoseok** [comment]
넵 수정해서 pr 날리도록 하겠습니다!
