### ISSUE TITLE
[LOGIC] 자신의 뷰 작성에 필요한 Firebase 데이터 얘기해주세요!

### ISSUE THREAD

**Issue by unuhqueen** [DeveloperAcademy-POSTECH/toGather#44]
비트 @yeongwooCho 랜스 @limhyoseok 밀러 @KimDaeSeong8721 닐 @yudonlee 맥스 @Sungwooo 이브@unuhqueen

## 💡 Issue

각자 뷰마다 Firebase에서 업로드 해야 하는 데이터, 또는 받아야 하는 데이터가 있을 것입니다.
그 데이터를 저희 model에 있는 형식으로 얘기해 주세요.

ex)
- 업로드 해야 하는 데이터
```swift
struct Saving {
  var startDate
  var goalWeeks
}
```
 
## 📝  todo
- [ ] 각자의 뷰에 필요한 Firebase 데이터 comment로 작성하기

**Comment by limhyoseok** [comment]
## 업로드 해야하는 데이터

<img width="572" alt="image" src="https://user-images.githubusercontent.com/59302419/173695566-ee55680a-7758-45e6-ac26-7f71da1be125.png">

- 전체 저축 주(기간)
- 첫번째 저축 시작날짜
- 저축요일
- 매주 저축 금액

**Comment by limhyoseok** [comment]
let savingAmount를 let savingAmountOfWeek로 변경했습니다

**Comment by limhyoseok** [comment]
하면서 궁금한 점을 몇가지 적었습니다.
1. User 객체에서 친구 정보를 담는 변수는 없던데 다른 곳에 존재하나요?
2. 사진 정보를 담는 객체는 어딘가요? (만약 안 정했다면  ThisWeek에 `var imageUrl: String?` 변수 추가하면 좋을 것 같습니다.)
3. 알림 데이터가 어떻게 구성되어 있는지 잘몰라서 일단 ??로 적어놨습니다.
4. Saving 객체에 들어있는 모든 정보를 파이어베이스에 저장하는지?

그래서 일단 친구정보는 User객체, 사진정보는 ThisWeek에 있다고 가정했습니다.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/59302419/174461682-9ce4c6a0-8a71-458f-88b2-cad6a5b46d0e.png">

빨간색 박스 - 파이어베이스 데이터 추가, 수정, 삭제 
파란색 박스 - 파이어베이스에서 데이터 가져오기
