### ISSUE TITLE
[FEAT] 알림창 UI & 기능구현

### ISSUE THREAD

**Issue by KimDaeSeong8721** [DeveloperAcademy-POSTECH/toGather#47]
## 💡 Issue

![알림창](https://user-images.githubusercontent.com/69894461/173529644-7b0b39a8-f7d8-424e-9c87-e6c3c46f39df.png)
## 📝  todo

- [ ] 알림창 UI
- [ ]  알림기능 구현

**Comment by limhyoseok** [comment]
percentage는 제가 드릴테니 따로 구현하지 않으셔도 됩니다!
