### ISSUE TITLE
[FEAT] User struct 데이터 구조 변경

### ISSUE THREAD

**Issue by limhyoseok** [DeveloperAcademy-POSTECH/toGather#60]
## 💡 Issue

|기존|변경|
|-|-|
|<img width="484" alt="image" src="https://user-images.githubusercontent.com/59302419/173726361-d7d0a54a-d8b9-49e2-9445-00b7372679c3.png">|<img width="480" alt="image" src="https://user-images.githubusercontent.com/59302419/173726275-bd0746f6-449e-428a-9c9f-9dd96053cfef.png">
- saveInfo 추가 : 목표 제품, 저축 요일 등... 저축에 관련된 정보가 담긴 struct를 추가 : User와 Saving이 분리되어있어 하나하나 하드코딩되고 있는 상황을 해결하기 위해서
- var isAlarmON: Bool? = false ->  var isAlarmON: Bool? 로 변경 : 옵셔널 형식에 디폴트 값이 들어있어서 제거

## 📝  todo
- [ ] 코드 수정 후 pr

**Comment by KimDaeSeong8721** [comment]
User랑 Saving을 분리 해놓은 이유는 파이어베이스에서 컬렉션 각각 따로 만들어서 id로 연결시켜주려고 했었습니다. 데이터베이스 테이블이 너무 커지면, 데이터를 가져올때 필요한 데이터만 가져오면 되는데 사용되지 않는 데이터들도 가져오게 되서 로딩이 늘어질 수 있다고 생각했습니다.

두번째 안건은 디폴트 값 제거해도 괜찮을 거 같습니다.

**Comment by limhyoseok** [comment]
해당 구조 변경은 앱 내에서 저희가 사용하는 struct 구조입니다. 파이어 베이스 내부 데이터 구조는user와 saving 분리하도록 하고 앱 내에서만 합쳐서 쓰는 것은 어떠신가요?

**Comment by KimDaeSeong8721** [comment]
좋습니다!
